//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamsResults
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accruals_And_Taxes
    {
        public int ID { get; set; }
        public Nullable<int> ID_Exam_Result { get; set; }
        public Nullable<int> ID_Payment_Bets { get; set; }
        public Nullable<decimal> Accrued { get; set; }
        public Nullable<decimal> NDFL { get; set; }
        public Nullable<decimal> Social_Tax { get; set; }
        public Nullable<decimal> To_Be_Paid { get; set; }
        public Nullable<System.DateTime> Date_Of_Calculation { get; set; }
    
        public virtual Exam_Results Exam_Results { get; set; }
        public virtual Payment_bets Payment_bets { get; set; }
    }
}
