//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamsResults
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExamsResultsEntities : DbContext
    {
        public ExamsResultsEntities()
            : base("name=ExamsResultsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accruals_And_Taxes> Accruals_And_Taxes { get; set; }
        public virtual DbSet<Exam_Results> Exam_Results { get; set; }
        public virtual DbSet<Examiners> Examiners { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Payment_bets> Payment_bets { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
