//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamsResults
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_bets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment_bets()
        {
            this.Accruals_And_Taxes = new HashSet<Accruals_And_Taxes>();
        }
    
        public int ID { get; set; }
        public int ID_Examiners { get; set; }
        public int ID_Subject { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accruals_And_Taxes> Accruals_And_Taxes { get; set; }
        public virtual Examiners Examiners { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
